const nsquestions = [
    { question: "What is the binary equivalent of the decimal number 10?", options: ["1010", "1100", "1001", "1110"], answer: "1010", category: "numbersystem" },
    { question: "What is the hexadecimal equivalent of the binary number 1111?", options: ["F", "E", "D", "C"], answer: "F", category: "numbersystem" },
    { question: "Which base is used in the octal number system?", options: ["2", "8", "10", "16"], answer: "8", category: "numbersystem" },
    { question: "Which is the following character is available in EBCDIC but not in ASCII?", options: ["cent sign","dollar sign","comma","punctuation"], answer: "cent sign", category: "number system" },
    { question: "A group od bits used to represent a symbol is called a ....", options: ["byte","memory","nibble","code"], answer: "byte", category: "number system" },
    { question: "BCD uses 6 bits to represents a symbol.", options: ["TRUE","FALSE","Nothing can be said","None of the mentioned"], answer: "TRUE", category: "number system" },
    { question: "Which of the following is not a type of computer code?", options: ["EBCDIC","BCD","ASCII","EDIC"], answer: "EDIC", category: "number system" },
    { question: "The BCD representation of 34(10) is.....", options: ["6.0","7.0","8.0","5.0"], answer: "7.0", category: "number system" },
    { question: "Perform BCD addition of (23)BCD + (20)BCD.", options: ["110100","1000011","100011","11100"], answer: "1000011", category: "number system" },
    { question: "The weights used in Binary Coded Decimal code are:", options: ["4,2,1","8,4,2,1","6,4,2,1","2,1"], answer: "8,4,2,1", category: "number system" },
    { question: "Write the decimal equivalent for (110001)BCD.", options: ["31","13","C1","1C"], answer: "31", category: "number system" },
    { question: "The 9's complement of 45 is ....", options: ["45","54","64","46"], answer: "54", category: "number system" },
    { question: "The 10's complement of 455 is....", options: ["543","544","545","546"], answer: "545", category: "number system" },
    { question: "the Excess-3 representation of (0100)BCD is ...", options: ["110","1110","111","1100"], answer: "111", category: "number system" },
    { question: "The numbers used to represent numeric values in EBCDIC are.... ", options: ["zoned","unsigned","packed","eb"], answer: "zoned", category: "number system" },
    { question: "Unicode provides a consistent way of encoding multilingual plain text.", options: ["TRUE","FAlSE","Nothing can be said","None of the mentioned"], answer: "TRUE", category: "number system" },
    { question: "Which of the following is not a type of numeric value in zoned format?", options: ["Positive ","Negative","Double","Unigned"], answer: "Double", category: "number system" },
    { question: "The sign indicator of unsigned numbers is....", options: ["C","D","F","X"], answer: "F", category: "number system" },
    { question: "The EBCDIC value of the number 345 in zoned format is....", options: ["F3F4F5","E3E4E5","F3F4C5","F3F4D5"], answer: "F3F4F5", category: "number system" },
    { question: "Which of the following is a valid encoding format?", options: ["UTF-1","UTF-8","UUTF-A","UTF-4"], answer: "UTF-8", category: "number system" },
    { question: "....define the assigned ordering among the characters used by the computer.", options: ["Unicode","Collating Sequence","Accumulation","Sorting"], answer: "Collating Sequence", category: "number system" },
    { question: "The sorting sequence of the strings A1,23,1A will be.....", options: ["23>A1>1A","23<1A>A1","A1>1A>23","A1<1A<23"], answer: "A1<1A<23", category: "number system" },
    { question: "The default character coding in HTML-5 is ....", options: ["UTF-8","UTF-16","UTF-4","UTF-32"], answer: "UTF-8", category: "number system" },
    { question: "Numbers used in packed decimal format can be used for .... operations.", options: ["logical","relational","bitwise","arithmetic"], answer: "arithmetic", category: "number system" },
    { question: "What does ASCII stand for?", options: ["American Standard Code for information Interchange","American Scientific Code for information interchange","American Scientific Code for Interchanging Information","American Standard Code for Interchanging Information"], answer: "American Standard Code for information Interchange", category: "number system" },
    { question: "The decimal representation for  the character ! in ASCII is ....", options: ["31","32","33","34"], answer: "33", category: "number system" },
    { question: "The two types of ASCII are.... and .....", options: ["ASCII-44 and ASCII-8","ASCII-8 and ASCII-16","ASCII-7 and ASCII-8","ASCII-4 and ASCII- 16"], answer: "ASCII-7 and ASCII-8", category: "number system" },
    { question: "Any set of digits or alphabets are generally referred as.....", options: ["Characters","symbols","Bits ","Bytes"], answer: "Characters", category: "number system" },
    { question: "The number of characters that can be represented in ASCII-8 are....", options: ["128","256","32","64"], answer: "256", category: "number system" },
    { question: "The zone of alphabetic characters from A to O in ASCII is  ", options: ["1000","100","10","1"], answer: "100", category: "number system" },
    { question: "The representation of the number 8 in binary in ASCII-8 format", options: ["111000","1001000","1000","11000"], answer: "111000", category: "number system" },
    { question: "Binary Coding for the letter X is ", options: ["1011000","111000","1.0001E7","10100"], answer: "1011000", category: "number system" },
    { question: ".... is a straightforward method of representing positive and negative numbers.", options: ["RAdix","Complement","Sign Magnitude","Encode"], answer: "Sign Magnitude", category: "number system" },
    { question: "additive inverse of a number is the number which when added to the original number gives 1 as a result.", options: ["TRUE","FALSE","Nothing can be said","None of the mentioned"], answer: "FALSE", category: "number system" },
    { question: "The 1's complement of 1 in 4 bits is...", options: ["1","0","1001","1110"], answer: "1110", category: "number system" },
    { question: "The binary number 111 in its 2's complements form is ", options: ["10","1","0","111"], answer: "1", category: "number system" },
    { question: "The sign magnitude representation of -9 is ", options: ["1001","1.1111001E7","1.0001001E7","11001"], answer: "1.0001001E7", category: "number system" },
    { question: "you are given a word of size of n bits, the range of 2's complement of binary numbers is ", options: ["-2n+1 to 2n+1","-2n-1 to +2n-1","-2n-1 to +2n+1","-2n-1 to +2n-1-1"], answer: "-2n-1 to +2n-1-1", category: "number system" },
    { question: "In both signed magnitude and 2's complement, positive and nagaative numbers are separated using....", options: ["LSB","MSB","0.0","1.0"], answer: "MSB", category: "number system" },
    { question: "Sigle Precision format comprises of ...bits", options: ["4","8","16","32"], answer: "32", category: "number system" },
    { question: "m is the 2's complement and n is the binary number, then..", options: ["m=n'","m=n'+1","m=n'-1","m=n"], answer: "m=n'+1", category: "number system" },
    { question: "The possible number of bit patterns with 8 bits ", options: ["128","8","24","256"], answer: "256", category: "number system" },
    { question: "Which of the following is used for binary multiplication?", options: ["Restoring Multiplication","Booth's Algorithm","Pascal's Rule ","Digit-by-digit multiplication"], answer: "Booth's Algorithm", category: "number system" },
    { question: "One extra bit is added on the left of a binary number, in case of Binary Multiplication using BOOth's Algorithm.", options: ["True","False","Nothing Can be used ","None of the mentioned"], answer: "True", category: "number system" },
    { question: "The binary number obtained after applying RSC on 11010 will be ", options: ["11101","10100","1101","1000"], answer: "1101", category: "number system" },
    { question: "The result of >>1101 by 3-bits will be..", options: ["1000","1111","11","11111"], answer: "1000", category: "number system" },
    { question: "Booth's Algorithm is applied on ", options: ["decimal numbers","binary numbers","hexadecimal numbers","octal numbers"], answer: "binary numbers", category: "number system" },
    { question: "If Booth's Multiplication is performed on the numbers 22*3. then what referred to as", options: ["accumulator","multipilcand","quotient","multiplier"], answer: "multiplier", category: "number system" },
    { question: "What is the default value of accumulator in booth's multiplication of to 4-bit binary numbers?", options: ["0","1","10","01"], answer: "0", category: "number system" },
    { question: "What is the value of n in multiplication of 110*1000?", options: ["2","3","4","5"], answer: "4", category: "number system" },
    { question: "The 2's complement of the binary number 1010 is...", options: ["0101", "0110", "1101", "1110"], answer: "0110", category: "numbersystem" },
    { question: "What is the hexadecimal representation of the decimal number 255?", options: ["FF", "FE", "FD", "FC"], answer: "FF", category: "numbersystem" },
    { question: "Which of the following is a valid binary number?", options: ["102", "1101", "2100", "3001"], answer: "1101", category: "numbersystem" },
    { question: "What is the octal equivalent of the binary number 101010?", options: ["52", "42", "62", "32"], answer: "52", category: "numbersystem" },
    { question: "What is the decimal equivalent of the binary number 1101?", options: ["13", "14", "15", "12"], answer: "13", category: "numbersystem" },
    { question: "In which number system does 'A' represent 10?", options: ["Binary", "Octal", "Decimal", "Hexadecimal"], answer: "Hexadecimal", category: "numbersystem" }
];
